
# i3 window manager configuration
i3: |
  exec_always feh --bg-fill /opt/leef/wallpapers/leaves.jpg
  bindsym Ctrl+Print exec --no-startup-id maim --format=png | xclip -selection clipboard -t image/png
  bindsym Ctrl+$mod+Print exec --no-startup-id maim --format=png --window $(xdotool getactivewindow) | xclip -selection clipboard -t image/png
  bindsym Ctrl+Shift+Print exec --no-startup-id maim --format=png --select | xclip -selection clipboard -t image/png  
